#!/bin/bash

## Define a resusable function
remove_Profile() {
targetProfileName="$1"
## Get UUID of requested Configuration Profile
profileUUID=`profiles -Lv | grep "$targetProfileName" -4 | awk -F": " '/attribute: profileIdentifier/{print $NF}'`

## Remove said profile, identified by UUID
if [[ $profileUUID ]]; then
    profiles -R -p $profileUUID
else
    echo "No Profile Found"
fi
## Take a break between each
sleep 2
}

## Use parameters passed to the script, ignoring first 3 parameters for compatibility with Capser MDM
## Comment out for other use cases
shift;shift;shift

# Iterate over remaining parameters
while test ${#} -gt 0
do
  echo -n "Removing profile "$1"... "; remove_Profile "$1"
  shift
done
exit 0

